/**
 * services/blockchainService.js
 *
 * Wraps Ethers.js v6 to interact with EvidenceManager.sol.
 *
 * Contract public interface (from IEvidenceManager.sol):
 *   registerEvidence(bytes32 _fileHash, string _metadataCid) → uint256 evidenceId
 *   transferCustody(uint256 _evidenceId, address _newCustodian)   [onlyCustodian]
 *   getEvidenceDetails(uint256 _evidenceId) → (bytes32, string, address, uint256)
 *
 * The contract uses:
 *   require(_fileHash != bytes32(0), "Invalid file hash")   ← enforced in Solidity
 *   nextEvidenceId auto-increments                          ← parsed from event
 */

const { ethers } = require("ethers");
const ABI        = require("../config/contractABI");

let provider, signer, contract;

// ─────────────────────────────────────────────────────────────────────────────
// init() — call once at server startup
// ─────────────────────────────────────────────────────────────────────────────
function init() {
  const rpcUrl       = process.env.RPC_URL;
  const privateKey   = process.env.PRIVATE_KEY;
  const contractAddr = process.env.CONTRACT_ADDRESS;

  if (!rpcUrl || !privateKey || !contractAddr) {
    throw new Error(
      "Missing required env vars: RPC_URL, PRIVATE_KEY, CONTRACT_ADDRESS"
    );
  }

  provider = new ethers.JsonRpcProvider(rpcUrl);
  signer   = new ethers.Wallet(privateKey, provider);
  contract = new ethers.Contract(contractAddr, ABI, signer);

  console.log(`🔗  Contract connected at ${contractAddr}`);
  return contract;
}

// ─────────────────────────────────────────────────────────────────────────────
// registerEvidence
//   Calls: registerEvidence(bytes32 _fileHash, string _metadataCid)
//   Note:  _fileHash must not be bytes32(0) — validated in Solidity
//
//   @param {string} fileHashHex  "0x" + 64 hex chars (from hashService)
//   @param {string} metadataCid  IPFS CID from Pinata
//   @returns {{ evidenceId, txHash, blockNumber }}
// ─────────────────────────────────────────────────────────────────────────────
async function registerEvidence(fileHashHex, metadataCid) {
  _ensureInit();

  // Guard against zero-hash (would revert on-chain, better to fail early)
  if (fileHashHex === "0x" + "0".repeat(64)) {
    throw new Error("File hash must not be zero (bytes32(0))");
  }

  const tx      = await contract.registerEvidence(fileHashHex, metadataCid);
  const receipt = await tx.wait(1); // wait for 1 confirmation

  // Parse evidenceId from EvidenceRegistered event
  let evidenceId = null;
  for (const log of receipt.logs) {
    try {
      const parsed = contract.interface.parseLog(log);
      if (parsed?.name === "EvidenceRegistered") {
        evidenceId = parsed.args.evidenceId.toString();
        break;
      }
    } catch (_) { /* not our event */ }
  }

  return {
    evidenceId,                    // auto-generated by nextEvidenceId counter
    txHash:      receipt.hash,
    blockNumber: receipt.blockNumber,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// transferCustody
//   Calls: transferCustody(uint256 _evidenceId, address _newCustodian)
//   Solidity modifier: onlyCustodian → reverts if caller isn't current custodian
//
//   @param {string|number} evidenceId
//   @param {string}        newCustodian  Ethereum address
//   @returns {{ txHash, blockNumber }}
// ─────────────────────────────────────────────────────────────────────────────
async function transferCustody(evidenceId, newCustodian) {
  _ensureInit();

  if (!ethers.isAddress(newCustodian)) {
    throw new Error(`Invalid Ethereum address: ${newCustodian}`);
  }

  const tx      = await contract.transferCustody(evidenceId, newCustodian);
  const receipt = await tx.wait(1);

  return {
    txHash:      receipt.hash,
    blockNumber: receipt.blockNumber,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// getEvidenceDetails
//   Calls: getEvidenceDetails(uint256 _evidenceId)
//   Returns the on-chain Evidence struct fields as a plain JS object.
//
//   Struct on-chain:
//     bytes32  fileHash
//     string   metadataCid
//     address  currentCustodian
//     uint256  registrationTimestamp
// ─────────────────────────────────────────────────────────────────────────────
async function getEvidenceDetails(evidenceId) {
  _ensureInit();

  const r = await contract.getEvidenceDetails(evidenceId);

  return {
    fileHash:              r.fileHash,                       // bytes32 hex string
    metadataCid:           r.metadataCid,                   // IPFS CID
    currentCustodian:      r.currentCustodian,              // address
    registrationTimestamp: Number(r.registrationTimestamp), // unix seconds
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
function _ensureInit() {
  if (!contract) throw new Error("blockchainService not initialised. Call init() first.");
}

/** Expose the raw contract instance (useful for event listeners in future) */
function getContract() {
  _ensureInit();
  return contract;
}

module.exports = { init, registerEvidence, transferCustody, getEvidenceDetails, getContract };
